[package]
name = "csv-inserter"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1"
clickhouse = "0.14.2"
clap = { version = "4", features = ["derive"] }
env_logger = "0.11"
log = "0.4"
notify = "8.2.0"
thiserror = "2"
tokio = { version = "1", features = ["full"] }
